import styles from "./index.module.css";
import { type NextPage } from "next";
import Head from "next/head";
import { useSession } from "next-auth/react";
import Layout from "@/components/Layout";
import Welcome from "@/components/Welcome";
import Header from "@/components/Header";
import MainPage from "@/components/Mainpage";

const Home: NextPage = () => {
    const { data: sessionData } = useSession();
    return (
        <>
            <Head>
                <title>Mockbook</title>
                <meta name='description' content='Generated by create-t3-app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <Layout>
                {!sessionData?.user ? (
                    <Welcome />
                ) : (
                    <main>
                        <Header />
                        <MainPage />
                    </main>
                )}
            </Layout>
        </>
    );
};

export default Home;
